### ISSUE TITLE
Errors found by the locate mod error function

### ISSUE THREAD

**Issue by nizhuan-jjr** [Caballero-Arepa/Latin-American_Civs#57]
Argentina's colors do not contrast enough - it is unreadable!
Suggested colors: 
		"outerColor": [81, 120, 156],
		"innerColor": [250, 217, 136],
Mexico's colors do not contrast enough - it is unreadable!
Suggested colors: 
		"outerColor": [0, 79, 54],
		"innerColor": [210, 132, 95],
Colon Free Port's unique "[+1 Production] from every [Trading post] [in this city]" looks like it may be a misspelling of:
	"[stats] from every [tileFilter/specialist/buildingFilter]"
Colon Free Port's unique "[+1 Production] from every [Trading post] [in this city]" looks like it may be a misspelling of:
	"[stats] from every [tileFilter/specialist/buildingFilter]"
![Screenshot_20230524_093637_com unciv app](https://github.com/Caballero-Arepa/Latin-American_Civs/assets/3255986/f9b22be4-fa03-414e-aef4-4c5f6d385840)

**Comment by Caballero-Arepa** [comment]
Hi.

Yes, I am aware of this so-called "Error", though it's not.

First, these errors do not affect the functioning of the mod in any way, so, don't worry about them.

Second, it has been a long since these appeared, and I tested trying the suggestions and these were the results:
![imagen](https://github.com/Caballero-Arepa/Latin-American_Civs/assets/78449553/048d77d6-3759-4f34-b0f4-9b22e300bb44)

In the end, I didn't like the proposals for Argentina, nor México, nor Cuba, so they stayed as they were.

**Comment by nizhuan-jjr** [comment]
I'm more concerned with this one. 
Colon Free Port's unique "[+1 Production] from every [Trading post] [in this city]" looks like it may be a misspelling of:
"[stats] from every [tileFilter/specialist/buildingFilter]"

According to the modding guide's unique& unique parameters section and my experience, the square bracket version of "in this city" means cityFilter. So you might want to use "<in this city>" to apply a conditional unique to "[stats] from every [tileFilter/specialist/buildingFilter]".
"[stats] from every [tileFilter/specialist/buildingFilter][cityFilter]" is not a legit global unique.
